package structs

import "gezgin_web_engine/cssParser/enums"

type CssProperties struct {
	//this could be bit field
	AccentColorInherit        bool
	AlignContentInherit       bool
	AlignItemsInherit         bool
	AlignSelfInherit          bool
	AnimationInherit          bool
	BackdropFilterInherit     bool
	BackfaceVisibilityInherit bool
	BackgroundInherit         bool
	BorderInherit             bool
	BorderCollapseInherit     bool
	BorderImageInherit        bool
	BorderRadiusInherit       bool
	BorderSpacingInherit      bool
	ColorInherit              bool
	FontInherit               bool
	TextAlignInherit          bool
	TextAlignLastInherit      bool
	TextDecorationInherit     bool
	TextIndentInherit         bool
	TextJustifyInherit        bool
	TextOverflowInherit       bool
	TextShadowInherit         bool
	TextTransformInherit      bool
	ColumnCountInherit        bool
	ColumnFillInherit         bool
	ColumnGapInherit          bool
	ColumnRuleInherit         bool
	ColumnSpanInherit         bool
	ColumnWidthInherit        bool
	FlexInherit               bool
	FlexFlowInherit           bool
	PositionInherit           bool
	WidthInherit              bool
	MinWidthInherit           bool
	MaxWidthInherit           bool
	HeightInherit             bool
	MinHeightInherit          bool
	MaxHeightInherit          bool
	TopInherit                bool
	LeftInherit               bool
	RightInherit              bool
	BottomInherit             bool
	MarginInherit             bool
	OutlineInherit            bool
	OverflowInherit           bool
	PaddingInherit            bool
	VisibilityInherit         bool
	OpacityInherit            bool
	ResizeInherit             bool

	AccentColor        *ColorRGBA
	AlignContent       enums.CssAlignType
	AlignItems         enums.CssAlignType
	AlignSelf          enums.CssAlignType
	Animation          *Animation
	Background         *Background
	BackdropFilter     enums.CssFilterType
	Border             *Border
	BorderCollapseType enums.CssBorderCollapseType
	Color              *ColorRGBA
	Display            enums.CssDisplayType
	Font               *Font
	Margin             *Margin
	Padding            *Padding
	Height             uint
	Width              uint
	MinHeight          uint
	MaxHeight          uint
	MinWidth           uint
	MaxWidth           uint
	Top                uint
	Bottom             uint
	Left               uint
	Right              uint
	HeightValueType    enums.CssPropertyValueType
	MinHeightValueType enums.CssPropertyValueType
	MaxHeightValueType enums.CssPropertyValueType
	WidthValueType     enums.CssPropertyValueType
	MinWidthValueType  enums.CssPropertyValueType
	MaxWidthValueType  enums.CssPropertyValueType
	Position           enums.CssPositionType
	TopValueType       enums.CssPropertyValueType
	BottomValueType    enums.CssPropertyValueType
	LeftValueType      enums.CssPropertyValueType
	RightValueType     enums.CssPropertyValueType
	Visibility         enums.CssVisibilityType
}
