package enums

type CssAnimationTimingFunctionType uint8
type CssAnimationDirectionType uint8
type CssAnimationFillModeType uint8
type CssAnimationPlayStateType uint8
type CssFilterType uint8
type CssAlignType uint8
type CssVisibilityType uint8
type CssBackgroundType uint8
type CssBackgroundPositionType uint8
type CssBackgroundRepeatType uint8
type CssBackgroundSizeType uint8
type CssBackgroundAttachmentType uint8
type CssBackgroundBlendModeType uint8
type CssBackgroundClipType uint8
type CssBackgroundOriginType uint8
type CssBorderlineType uint8
type CssBorderStyleType uint8
type CssBorderRadiusType uint8
type CssBorderCollapseType uint8
type CssBorderImageSourceType uint8
type CssBorderImageSliceType uint8
type CssBorderImageWidthType uint8
type CssBorderImageOutsetType uint8
type CssBorderImageRepeatType uint8
type CssPropertyValueType uint8
type CssBoxDecorationType uint8
type CssBoxSizingType uint8
type CssBreakType uint8
type CssCaptionSideType uint8
type CssClearType uint8
type CssClipType uint8
type CssColumnFillType uint8
type CssColumnRuleStyleType uint8
type CssColumnRuleWidthType uint8
type CssColumnSpanType uint8
type CssCursorType uint8
type CssDirectionType uint8
type CssDisplayType uint8
type CssEmptyCellsType uint8
type CssFlexDirectionType uint8
type CssFlexWrapType uint8
type CssFloatType uint8
type CssFontType uint8
type CssFontVariantType uint8
type CssFontWeightType uint8
type CssFontStyleType uint8
type CssFontSizeType uint8
type CssFontStretchType uint8
type CssFontVariantCapsType uint8
type CssFontSpecialType uint8
type CssGridAutoFlowType uint8
type CssTextAlignType uint8
type CssTextDecorationLineType uint8
type CssTextDecorationStyleType uint8
type CssTextDecorationThicknessType uint8
type CssTextJustifyType uint8
type CssTextOverflowType uint8
type CssTextTransformType uint8
type CssPositionType uint8
type CssOutlineWidthType uint8
type CssOutlineStyleType uint8
type CssOverflowType uint8
type CssOverflowWrapType uint8
type CssResizeType uint8

const (
	CSS_ANIMATION_TIMING_FUNCTION_LINEAR CssAnimationTimingFunctionType = iota
	CSS_ANIMATION_TIMING_FUNCTION_EASE
	CSS_ANIMATION_TIMING_FUNCTION_EASE_IN
	CSS_ANIMATION_TIMING_FUNCTION_EASE_OUT
	CSS_ANIMATION_TIMING_FUNCTION_EASE_IN_OUT
	CSS_ANIMATION_TIMING_FUNCTION_STEP_START
	CSS_ANIMATION_TIMING_FUNCTION_STEP_END
)

const (
	CSS_ANIMATION_DIRECTION_NORMAL CssAnimationDirectionType = iota
	CSS_ANIMATION_DIRECTION_REVERSE
	CSS_ANIMATION_DIRECTION_ALTERNATE
	CSS_ANIMATION_DIRECTION_ALTERNATE_REVERSE
)

const (
	CSS_ANIMATION_FILL_MODE_NONE CssAnimationFillModeType = iota
	CSS_ANIMATION_FILL_MODE_FORWARDS
	CSS_ANIMATION_FILL_MODE_BACKWARDS
	CSS_ANIMATION_FILL_MODE_BOTH
)

const (
	CSS_ANIMATION_PLAY_STATE_PAUSED CssAnimationPlayStateType = iota
	CSS_ANIMATION_PLAY_STATE_RUNNING
)

const (
	CSS_FILTER_TYPE_EMPTY CssFilterType = iota
	CSS_FILTER_TYPE_NONE
	CSS_FILTER_TYPE_BLUR
	CSS_FILTER_TYPE_BRIGHTNESS
	CSS_FILTER_TYPE_CONTRAST
	CSS_FILTER_TYPE_DROP_SHADOW
	CSS_FILTER_TYPE_GRAYSCALE
	CSS_FILTER_TYPE_HUE_ROTATE
	CSS_FILTER_TYPE_INVERT
	CSS_FILTER_TYPE_OPACITY
	CSS_FILTER_TYPE_SATURATE
	CSS_FILTER_TYPE_SEPIA
	CSS_FILTER_TYPE_URL
)

const (
	CSS_ALIGN_EMPTY CssAlignType = iota
	CSS_ALIGN_STRETCH
	CSS_ALIGN_CENTER
	CSS_ALIGN_FLEX_START
	CSS_ALIGN_FLEX_END
	CSS_ALIGN_SPACE_BETWEEN
	CSS_ALIGN_SPACE_AROUND
	CSS_ALIGN_SPACE_EVENLY
	CSS_ALIGN_BASELINE
	CSS_ALIGN_AUTO
)

const (
	CSS_VISIBILITY_EMPTY CssVisibilityType = iota
	CSS_VISIBILITY_VISIBLE
	CSS_VISIBILITY_HIDDEN
	CSS_VISIBILITY_COLLAPSE
)

const (
	CSS_BACKGROUND_TYPE_URL CssBackgroundType = iota
	CSS_BACKGROUND_TYPE_CONIC_GRADIENT
	CSS_BACKGROUND_TYPE_LINEAR_GRADIENT
	CSS_BACKGROUND_TYPE_RADIAL_GRADIENT
	CSS_BACKGROUND_TYPE_REPEATING_CONIC_GRADIENT
	CSS_BACKGROUND_TYPE_REPEATING_LINEAR_GRADIENT
	CSS_BACKGROUND_TYPE_REPEATING_RADIAL_GRADIENT
)

const (
	CSS_BACKGROUND_POSITION_TYPE_WORD CssBackgroundPositionType = iota
	CSS_BACKGROUND_POSITION_TYPE_PERCENT
	CSS_BACKGROUND_POSITION_TYPE_POS
)

const (
	CSS_BACKGROUND_REPEAT_TYPE_REPEAT CssBackgroundRepeatType = iota
	CSS_BACKGROUND_REPEAT_TYPE_REPEAT_X
	CSS_BACKGROUND_REPEAT_TYPE_REPEAT_Y
	CSS_BACKGROUND_REPEAT_TYPE_NO_REPEAT
	CSS_BACKGROUND_REPEAT_TYPE_ROUND
	CSS_BACKGROUND_REPEAT_TYPE_SPACE
)

const (
	CSS_BACKGROUND_SIZE_TYPE_AUTO CssBackgroundSizeType = iota
	CSS_BACKGROUND_SIZE_TYPE_LENGTH
	CSS_BACKGROUND_SIZE_TYPE_PERCENTAGE
	CSS_BACKGROUND_SIZE_TYPE_COVER
	CSS_BACKGROUND_SIZE_TYPE_CONTAIN
)

const (
	CSS_BACKGROUND_ATTACHMENT_SCROLL CssBackgroundAttachmentType = iota
	CSS_BACKGROUND_ATTACHMENT_FIXED
	CSS_BACKGROUND_ATTACHMENT_LOCAL
)

const (
	CSS_BACKGROUND_BLEND_MODE_NORMAL CssBackgroundBlendModeType = iota
	CSS_BACKGROUND_BLEND_MODE_MULTIPLY
	CSS_BACKGROUND_BLEND_MODE_SCREEN
	CSS_BACKGROUND_BLEND_MODE_OVERLAY
	CSS_BACKGROUND_BLEND_MODE_DARKEN
	CSS_BACKGROUND_BLEND_MODE_LIGHTEN
	CSS_BACKGROUND_BLEND_MODE_COLOR_DODGE
	CSS_BACKGROUND_BLEND_MODE_SATURATION
	CSS_BACKGROUND_BLEND_MODE_COLOR
	CSS_BACKGROUND_BLEND_MODE_LUMINOSITY
)

const (
	CSS_BACKGROUND_CLIP_BORDER_BOX CssBackgroundClipType = iota
	CSS_BACKGROUND_CLIP_PADDING_BOX
	CSS_BACKGROUND_CLIP_CONTENT_BOX
)

const (
	CSS_BACKGROUND_ORIGIN_PADDING_BOX CssBackgroundOriginType = iota
	CSS_BACKGROUND_ORIGIN_BORDER_BOX
	CSS_BACKGROUND_ORIGIN_CONTENT_BOX
)

const (
	CSS_BORDER_LINE_TYPE_MEDIUM CssBorderlineType = iota
	CSS_BORDER_LINE_TYPE_THIN
	CSS_BORDER_LINE_TYPE_THICK
	CSS_BORDER_LINE_TYPE_LENGTH
)

const (
	CSS_BORDER_STYLE_TYPE_NONE CssBorderStyleType = iota
	CSS_BORDER_STYLE_TYPE_HIDDEN
	CSS_BORDER_STYLE_TYPE_DOTTED
	CSS_BORDER_STYLE_TYPE_DASHED
	CSS_BORDER_STYLE_TYPE_SOLID
	CSS_BORDER_STYLE_TYPE_DOUBLE
	CSS_BORDER_STYLE_TYPE_GROOVE
	CSS_BORDER_STYLE_TYPE_RIDGE
	CSS_BORDER_STYLE_TYPE_INSET
	CSS_BORDER_STYLE_TYPE_OUTSET
)

const (
	CSS_BORDER_RADIUS_TYPE_LENGTH CssBorderRadiusType = iota
	CSS_BORDER_RADIUS_TYPE_PERCENTAGE
)

const (
	CSS_BORDER_COLLAPSE_TYPE_EMPTY CssBorderCollapseType = iota
	CSS_BORDER_COLLAPSE_TYPE_SEPARATE
	CSS_BORDER_COLLAPSE_TYPE_COLLAPSE
)

const (
	CSS_BORDER_IMAGE_SOURCE_TYPE_NONE CssBorderImageSourceType = iota
	CSS_BORDER_IMAGE_SOURCE_TYPE_IMAGE
)

const (
	CSS_BORDER_IMAGE_SLICE_TYPE_NUMBER CssBorderImageSliceType = iota
	CSS_BORDER_IMAGE_SLICE_TYPE_PERCENTAGE
	CSS_BORDER_IMAGE_SLICE_TYPE_FILL
)

const (
	CSS_BORDER_IMAGE_WIDTH_TYPE_LENGTH CssBorderImageWidthType = iota
	CSS_BORDER_IMAGE_WIDTH_TYPE_NUMBER
	CSS_BORDER_IMAGE_WIDTH_TYPE_PERCENTAGE
	CSS_BORDER_IMAGE_WIDTH_TYPE_AUTO
)

const (
	CSS_BORDER_IMAGE_OUTSET_TYPE_LENGTH CssBorderImageOutsetType = iota
	CSS_BORDER_IMAGE_OUTSET_TYPE_NUMBER
)

const (
	CSS_BORDER_IMAGE_REPEAT_TYPE_STRETCH CssBorderImageRepeatType = iota
	CSS_BORDER_IMAGE_REPEAT_TYPE_REPEAT
	CSS_BORDER_IMAGE_REPEAT_TYPE_ROUND
	CSS_BORDER_IMAGE_REPEAT_TYPE_SPACE
)

const (
	CSS_PROPERTY_VALUE_TYPE_EMPTY CssPropertyValueType = iota
	CSS_PROPERTY_VALUE_TYPE_AUTO
	CSS_PROPERTY_VALUE_TYPE_LENGTH
	CSS_PROPERTY_VALUE_TYPE_PIXEL
	CSS_PROPERTY_VALUE_TYPE_PERCENTAGE
	CSS_PROPERTY_VALUE_TYPE_NONE
	CSS_PROPERTY_VALUE_TYPE_NORMAL
	CSS_PROPERTY_VALUE_TYPE_MAX_CONTENT
	CSS_PROPERTY_VALUE_TYPE_MIN_CONTENT
	CSS_PROPERTY_VALUE_TYPE_SPAN
	CSS_PROPERTY_VALUE_TYPE_MINMAX
	CSS_PROPERTY_VALUE_TYPE_FIT_CONTENT
)

const (
	CSS_BOX_DECORATION_BREAK_TYPE_SLICE CssBoxDecorationType = iota
	CSS_BOX_DECORATION_BREAK_TYPE_CLONE
	CSS_BOX_DECORATION_BREAK_TYPE_UNSET
)

const (
	CSS_BOX_SIZING_TYPE_CONTENT_BOX CssBoxSizingType = iota
	CSS_BOX_SIZING_TYPE_BORDER_BOX
)

const (
	CSS_BREAK_TYPE_AUTO CssBreakType = iota
	CSS_BREAK_TYPE_ALL
	CSS_BREAK_TYPE_ALWAYS
	CSS_BREAK_TYPE_AVOID
	CSS_BREAK_TYPE_AVOID_COLUMN
	CSS_BREAK_TYPE_AVOID_PAGE
	CSS_BREAK_TYPE_AVOID_REGION
	CSS_BREAK_TYPE_COLUMN
	CSS_BREAK_TYPE_LEFT
	CSS_BREAK_TYPE_PAGE
	CSS_BREAK_TYPE_RECTO
	CSS_BREAK_TYPE_REGION
	CSS_BREAK_TYPE_RIGHT
	CSS_BREAK_TYPE_VERSO
)

const (
	CSS_CAPTION_SIDE_TOP CssCaptionSideType = iota
	CSS_CAPTION_SIDE_BOTTOM
)

const (
	CSS_CLEAR_TYPE_NONE CssClearType = iota
	CSS_CLEAR_TYPE_LEFT
	CSS_CLEAR_TYPE_RIGHT
	CSS_CLEAR_TYPE_BOTH
)

const (
	CSS_CLIP_TYPE_AUTO CssClipType = iota
	CSS_CLIP_TYPE_SHAPE
)

const (
	CSS_COLUMN_FILL_TYPE_EMPTY CssColumnFillType = iota
	CSS_COLUMN_FILL_TYPE_BALANCE
	CSS_COLUMN_FILL_TYPE_AUTO
)

const (
	CSS_COLUMN_RULE_STYLE_NONE CssColumnRuleStyleType = iota
	CSS_COLUMN_RULE_STYLE_HIDDEN
	CSS_COLUMN_RULE_STYLE_DOTTED
	CSS_COLUMN_RULE_STYLE_DASHED
	CSS_COLUMN_RULE_STYLE_SOLID
	CSS_COLUMN_RULE_STYLE_DOUBLE
	CSS_COLUMN_RULE_STYLE_GROOVE
	CSS_COLUMN_RULE_STYLE_RIDGE
	CSS_COLUMN_RULE_STYLE_INSET
	CSS_COLUMN_RULE_STYLE_OUTSET
)

const (
	CSS_COLUMN_RULE_WIDTH_TYPE_MEDIUM CssColumnRuleWidthType = iota
	CSS_COLUMN_RULE_WIDTH_TYPE_THIN
	CSS_COLUMN_RULE_WIDTH_TYPE_THICK
	CSS_COLUMN_RULE_WIDTH_TYPE_LENGTH
)

const (
	CSS_COLUMN_SPAN_TYPE_EMPTY CssColumnSpanType = iota
	CSS_COLUMN_SPAN_TYPE_NONE
	CSS_COLUMN_SPAN_TYPE_ALL
)

const (
	CSS_CURSOR_TYPE_ALIAS CssCursorType = iota
	CSS_CURSOR_TYPE_ALL_SCROLL
	CSS_CURSOR_TYPE_AUTO
	CSS_CURSOR_TYPE_CELL
	CSS_CURSOR_TYPE_CONTEXT_MENU
	CSS_CURSOR_TYPE_COL_RESIZE
	CSS_CURSOR_TYPE_COPY
	CSS_CURSOR_TYPE_CROSSHAIR
	CSS_CURSOR_TYPE_DEFAULT
	CSS_CURSOR_TYPE_E_RESIZE
	CSS_CURSOR_TYPE_EW_RESIZE
	CSS_CURSOR_TYPE_GRAB
	CSS_CURSOR_TYPE_GRABBING
	CSS_CURSOR_TYPE_HELP
	CSS_CURSOR_TYPE_MOVE
	CSS_CURSOR_TYPE_N_RESIZE
	CSS_CURSOR_TYPE_NE_RESIZE
	CSS_CURSOR_TYPE_NESW_RESIZE
	CSS_CURSOR_TYPE_NS_RESIZE
	CSS_CURSOR_TYPE_NW_RESIZE
	CSS_CURSOR_TYPE_NWSE_RESIZE
	CSS_CURSOR_TYPE_NO_DROP
	CSS_CURSOR_TYPE_NONE
	CSS_CURSOR_TYPE_NOT_ALLOWED
	CSS_CURSOR_TYPE_POINTER
	CSS_CURSOR_TYPE_PROGRESS
	CSS_CURSOR_TYPE_ROW_RESIZE
	CSS_CURSOR_TYPE_S_RESIZE
	CSS_CURSOR_TYPE_SE_RESIZE
	CSS_CURSOR_TYPE_SW_RESIZE
	CSS_CURSOR_TYPE_TEXT
	CSS_CURSOR_TYPE_URL
	CSS_CURSOR_TYPE_VERTICAL_TEXT
	CSS_CURSOR_TYPE_W_RESIZE
	CSS_CURSOR_TYPE_WAIT
	CSS_CURSOR_TYPE_ZOOM_IN
	CSS_CURSOR_TYPE_ZOOM_OUT
)

const (
	CSS_DIRECTION_TYPE_LTR CssDirectionType = iota
	CSS_DIRECTION_TYPE_RTL
)

const (
	CSS_DISPLAY_TYPE_BLOCK CssDisplayType = iota
	CSS_DISPLAY_TYPE_INLINE
	CSS_DISPLAY_TYPE_CONTENTS
	CSS_DISPLAY_TYPE_FLEX
	CSS_DISPLAY_TYPE_GRID
	CSS_DISPLAY_TYPE_INLINE_BLOCK
	CSS_DISPLAY_TYPE_INLINE_FLEX
	CSS_DISPLAY_TYPE_INLINE_GRID
	CSS_DISPLAY_TYPE_INLINE_TABLE
	CSS_DISPLAY_TYPE_LIST_ITEM
	CSS_DISPLAY_TYPE_RUN_IN
	CSS_DISPLAY_TYPE_TABLE
	CSS_DISPLAY_TYPE_TABLE_CAPTION
	CSS_DISPLAY_TYPE_TABLE_COLUMN_GROUP
	CSS_DISPLAY_TYPE_TABLE_HEADER_GROUP
	CSS_DISPLAY_TYPE_TABLE_FOOTER_GROUP
	CSS_DISPLAY_TYPE_TABLE_ROW_GROUP
	CSS_DISPLAY_TYPE_TABLE_CELL
	CSS_DISPLAY_TYPE_TABLE_COLUMN
	CSS_DISPLAY_TYPE_TABLE_ROW
	CSS_DISPLAY_TYPE_NONE
)

const (
	CSS_EMPTY_CELLS_TYPE_SHOW CssEmptyCellsType = iota
	CSS_EMPTY_CELLS_TYPE_HIDE
)

const (
	CSS_FLEX_DIRECTION_TYPE_ROW CssFlexDirectionType = iota
	CSS_FLEX_DIRECTION_TYPE_ROW_REVERSE
	CSS_FLEX_DIRECTION_TYPE_COLUMN
	CSS_FLEX_DIRECTION_TYPE_COLUMN_REVERSE
)

const (
	CSS_FLEX_WRAP_TYPE_NOWRAP CssFlexWrapType = iota
	CSS_FLEX_WRAP_TYPE_WRAP
	CSS_FLEX_WRAP_TYPE_WRAP_REVERSE
)

const (
	CSS_FLOAT_TYPE_NONE CssFloatType = iota
	CSS_FLOAT_TYPE_LEFT
	CSS_FLOAT_TYPE_RIGHT
)

const (
	CSS_FONT_STYLE_EMPTY CssFontStyleType = iota
	CSS_FONT_STYLE_NORMAL
	CSS_FONT_STYLE_ITALIC
	CSS_FONT_STYLE_OBLIQUE
)

const (
	CSS_FONT_VARIANT_EMPTY CssFontVariantType = iota
	CSS_FONT_VARIANT_NORMAL
	CSS_FONT_VARIANT_SMALL_CAPS
)

const (
	CSS_FONT_WEIGHT_EMPTY CssFontWeightType = iota
	CSS_FONT_WEIGHT_NORMAL
	CSS_FONT_WEIGHT_BOLD
	CSS_FONT_WEIGHT_BOLDER
	CSS_FONT_WEIGHT_LIGHTER
	CSS_FONT_WEIGHT_NUMBER
)

const (
	CSS_FONT_SIZE_TYPE_EMPTY CssFontSizeType = iota
	CSS_FONT_SIZE_TYPE_MEDIUM
	CSS_FONT_SIZE_TYPE_XX_SMALL
	CSS_FONT_SIZE_TYPE_X_SMALL
	CSS_FONT_SIZE_TYPE_SMALL
	CSS_FONT_SIZE_TYPE_LARGE
	CSS_FONT_SIZE_TYPE_X_LARGE
	CSS_FONT_SIZE_TYPE_XX_LARGE
	CSS_FONT_SIZE_TYPE_SMALLER
	CSS_FONT_SIZE_TYPE_LARGER
	CSS_FONT_SIZE_TYPE_LENGTH
	CSS_FONT_SIZE_TYPE_PERCENTAGE
)

const (
	CSS_FONT_STRETCH_TYPE_EMPTY CssFontStretchType = iota
	CSS_FONT_STRETCH_TYPE_ULTRA_CONDENSED
	CSS_FONT_STRETCH_TYPE_EXTRA_CONDENSED
	CSS_FONT_STRETCH_TYPE_CONDENSED
	CSS_FONT_STRETCH_TYPE_SEMI_CONDENSED
	CSS_FONT_STRETCH_TYPE_NORMAL
	CSS_FONT_STRETCH_TYPE_SEMI_EXPANDED
	CSS_FONT_STRETCH_TYPE_EXPANDED
	CSS_FONT_STRETCH_TYPE_EXTRA_EXPANDED
	CSS_FONT_STRETCH_TYPE_ULTRA_EXPANDED
)

const (
	CSS_FONT_VARIANT_CAPS_TYPE_EMPTY CssFontVariantCapsType = iota
	CSS_FONT_VARIANT_CAPS_TYPE_NORMAL
	CSS_FONT_VARIANT_CAPS_TYPE_SMALL_CAPS
	CSS_FONT_VARIANT_CAPS_TYPE_ALL_SMALL_CAPS
	CSS_FONT_VARIANT_CAPS_TYPE_PETITE_CAPS
	CSS_FONT_VARIANT_CAPS_TYPE_ALL_PETITE_CAPS
	CSS_FONT_VARIANT_CAPS_TYPE_UNICASE
	CSS_FONT_VARIANT_CAPS_TYPE_TITLING_CAPS
	CSS_FONT_VARIANT_CAPS_TYPE_UNSET
)

const (
	CSS_FONT_SANS CssFontType = iota
)

const (
	CSS_FONT_SPECIAL_TYPE_NONE CssFontSpecialType = iota
	CSS_FONT_SPECIAL_TYPE_CAPTION
	CSS_FONT_SPECIAL_TYPE_ICON
	CSS_FONT_SPECIAL_TYPE_MENU
	CSS_FONT_SPECIAL_TYPE_MESSAGE_BOX
	CSS_FONT_SPECIAL_TYPE_SMALL_CAPTION
	CSS_FONT_SPECIAL_TYPE_STATUS_BAR
)

const (
	CSS_GRID_AUTO_FLOW_TYPE_ROW CssGridAutoFlowType = iota
	CSS_GRID_AUTO_FLOW_TYPE_COLUMN
	CSS_GRID_AUTO_FLOW_TYPE_DENSE
	CSS_GRID_AUTO_FLOW_TYPE_ROW_DENSE
	CSS_GRID_AUTO_FLOW_TYPE_COLUMN_DENSE
)

const (
	CSS_TEXT_ALIGN_LEFT CssTextAlignType = iota
	CSS_TEXT_ALIGN_RIGHT
	CSS_TEXT_ALIGN_CENTER
	CSS_TEXT_ALIGN_JUSTIFY
	CSS_TEXT_ALIGN_START
	CSS_TEXT_ALIGN_END
)

const (
	CSS_TEXT_DECORATION_LINE_NONE CssTextDecorationLineType = iota
	CSS_TEXT_DECORATION_LINE_UNDERLINE
	CSS_TEXT_DECORATION_LINE_OVERLINE
	CSS_TEXT_DECORATION_LINE_LINE_THROUGH
)

const (
	CSS_TEXT_DECORATION_STYLE_SOLID CssTextDecorationStyleType = iota
	CSS_TEXT_DECORATION_STYLE_DOUBLE
	CSS_TEXT_DECORATION_STYLE_DOTTED
	CSS_TEXT_DECORATION_STYLE_DASHED
	CSS_TEXT_DECORATION_STYLE_WAVY
)

const (
	CSS_TEXT_DECORATION_THICKNESS_AUTO CssTextDecorationThicknessType = iota
	CSS_TEXT_DECORATION_THICKNESS_FROM_FONT
	CSS_TEXT_DECORATION_THICKNESS_FROM_LENGTH
	CSS_TEXT_DECORATION_THICKNESS_FROM_PERCENTAGE
)

const (
	CSS_TEXT_JUSTIFY_EMPTY CssTextJustifyType = iota
	CSS_TEXT_JUSTIFY_AUTO
	CSS_TEXT_JUSTIFY_INTER_WORD
	CSS_TEXT_JUSTIFY_INTER_CHARACTER
	CSS_TEXT_JUSTIFY_NONE
)

const (
	CSS_TEXT_OVERFLOW_EMPTY CssTextOverflowType = iota
	CSS_TEXT_OVERFLOW_CLIP
	CSS_TEXT_OVERFLOW_ELLIPSIS
	CSS_TEXT_OVERFLOW_STRING
)

const (
	CSS_TEXT_TRANSFORM_EMPTY CssTextTransformType = iota
	CSS_TEXT_TRANSFORM_NONE
	CSS_TEXT_TRANSFORM_CAPITALIZE
	CSS_TEXT_TRANSFORM_UPPERCASE
	CSS_TEXT_TRANSFORM_LOWERCASE
)

const (
	CSS_POSITION_TYPE_EMPTY CssPositionType = iota
	CSS_POSITION_TYPE_STATIC
	CSS_POSITION_TYPE_ABSOLUTE
	CSS_POSITION_TYPE_FIXED
	CSS_POSITION_TYPE_RELATIVE
	CSS_POSITION_TYPE_STICKY
)

const (
	CSS_OUTLINE_WIDTH_TYPE_MEDIUM CssOutlineWidthType = iota
	CSS_OUTLINE_WIDTH_TYPE_THIN
	CSS_OUTLINE_WIDTH_TYPE_THICK
	CSS_OUTLINE_WIDTH_TYPE_LENGTH
)

const (
	CSS_OUTLINE_STYLE_TYPE_NONE CssOutlineStyleType = iota
	CSS_OUTLINE_STYLE_TYPE_HIDDEN
	CSS_OUTLINE_STYLE_TYPE_DOTTED
	CSS_OUTLINE_STYLE_TYPE_DASHED
	CSS_OUTLINE_STYLE_TYPE_SOLID
	CSS_OUTLINE_STYLE_TYPE_DOUBLE
	CSS_OUTLINE_STYLE_TYPE_GROOVE
	CSS_OUTLINE_STYLE_TYPE_RIDGE
	CSS_OUTLINE_STYLE_TYPE_INSET
	CSS_OUTLINE_STYLE_TYPE_OUTSET
)

const (
	CSS_OVERFLOW_VISIBLE CssOverflowType = iota
	CSS_OVERFLOW_HIDDEN
	CSS_OVERFLOW_CLIP
	CSS_OVERFLOW_SCROLL
	CSS_OVERFLOW_AUTO
)

const (
	CSS_OVERFLOW_EMPTY CssOverflowWrapType = iota
	CSS_OVERFLOW_WRAP_NORMAL
	CSS_OVERFLOW_WRAP_ANYWHERE
	CSS_OVERFLOW_WRAP_BREAK_WORD
)

const (
	CSS_RESIZE_EMPTY CssResizeType = iota
	CSS_RESIZE_NONE
	CSS_RESIZE_BOTH
	CSS_RESIZE_HORIZONTAL
	CSS_RESIZE_VERTICAL
)
